import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="{`${geistSans.variable} ${geistMono.variable} antialiased`} min-h-screen pt-1un5 pb-19 bg-[#f4f1fb] text-[#3f2a25]"
      >
        <Navbar/>
        {children}
        <Footer/>
        <Toaster position="top-left" reverseOrder={false} />
      </body>

    </html>
  );
}
